// Autogenerated from Pigeon (v4.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, ErrorCode) {
  ErrorCodeInvalidUrl = 0,
  ErrorCodeJoin = 1,
  ErrorCodeUpdateCamera = 2,
  ErrorCodeUpdateMicrophone = 3,
};

@class VoidResult;
@class PlatformError;
@class JoinArgs;
@class JoinMessage;
@class LocalParticipantMessage;
@class RemoteParticipantMessage;

@interface VoidResult : NSObject
+ (instancetype)makeWithError:(nullable PlatformError *)error;
@property(nonatomic, strong, nullable) PlatformError * error;
@end

@interface PlatformError : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithMessage:(NSString *)message
    code:(ErrorCode)code;
@property(nonatomic, copy) NSString * message;
@property(nonatomic, assign) ErrorCode code;
@end

@interface JoinArgs : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUrl:(NSString *)url
    token:(NSString *)token
    enableMicrophone:(NSNumber *)enableMicrophone
    enableCamera:(NSNumber *)enableCamera;
@property(nonatomic, copy) NSString * url;
@property(nonatomic, copy) NSString * token;
@property(nonatomic, strong) NSNumber * enableMicrophone;
@property(nonatomic, strong) NSNumber * enableCamera;
@end

/// Returning class from join() function
@interface JoinMessage : NSObject
+ (instancetype)makeWithLocalParticipant:(nullable LocalParticipantMessage *)localParticipant
    remoteParticipants:(nullable NSArray<RemoteParticipantMessage *> *)remoteParticipants
    error:(nullable PlatformError *)error;
@property(nonatomic, strong, nullable) LocalParticipantMessage * localParticipant;
@property(nonatomic, strong, nullable) NSArray<RemoteParticipantMessage *> * remoteParticipants;
@property(nonatomic, strong, nullable) PlatformError * error;
@end

@interface LocalParticipantMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    isCameraEnabled:(NSNumber *)isCameraEnabled
    isMicrophoneEnabled:(NSNumber *)isMicrophoneEnabled
    userId:(NSString *)userId;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, strong) NSNumber * isCameraEnabled;
@property(nonatomic, strong) NSNumber * isMicrophoneEnabled;
@property(nonatomic, copy) NSString * userId;
@end

@interface RemoteParticipantMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    isCameraEnabled:(NSNumber *)isCameraEnabled
    isMicrophoneEnabled:(NSNumber *)isMicrophoneEnabled
    userId:(NSString *)userId;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, strong) NSNumber * isCameraEnabled;
@property(nonatomic, strong) NSNumber * isMicrophoneEnabled;
@property(nonatomic, copy) NSString * userId;
@end

/// The codec used by DailyMessenger.
NSObject<FlutterMessageCodec> *DailyMessengerGetCodec(void);

/// This is the base class of communication with native code.
/// It's used for generating the Pigeon files
@protocol DailyMessenger
/// Join Daily call.
- (void)joinArgs:(JoinArgs *)args completion:(void(^)(JoinMessage *_Nullable, FlutterError *_Nullable))completion;
/// Leave Daily call.
///
/// @return `nil` only when `error != nil`.
- (nullable VoidResult *)leaveWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable VoidResult *)setMicrophoneEnabledEnableMic:(NSNumber *)enableMic error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable VoidResult *)setCameraEnabledEnableCam:(NSNumber *)enableCam error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void DailyMessengerSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DailyMessenger> *_Nullable api);

NS_ASSUME_NONNULL_END
